name       : syncthing
version    : 0.14.44
release    : 34
homepage   : https://syncthing.net
source     :
    - https://github.com/syncthing/syncthing/releases/download/v0.14.44/syncthing-source-v0.14.44.tar.gz : 2136ef7bdec305f01fd9e7bde92d904bb9215e1e6328703b12a98015b828b83b
license    : MPL-2.0
extract    : no
component  : network.util
summary    : Syncthing is an open-source file synchronization client/server application
description: |
    Syncthing is an open-source file synchronization client/server application, written in Go, implementing its own, equally free Block Exchange Protocol. All transit communications between syncthing nodes are encrypted, and all nodes are uniquely identified with cryptographic certificates.
builddeps  :
    - golang
build      : |
    export GOPATH="${workdir}" GOROOT_FINAL="/usr/bin"
    export syncdir="${workdir}/src/github.com/syncthing/"
    mkdir -p $syncdir
    tar -xf $sources/syncthing-source-v${version}.tar.gz -C $syncdir
    cd $syncdir/syncthing
    go run build.go -no-upgrade -version v${version} build
install    : |
    export syncdir="${workdir}/src/github.com/syncthing/"
    cd $syncdir/syncthing
    # Install binaries and systemd stuff
    install -Dm00755 syncthing $installdir/usr/bin/syncthing
    install -Dm00644 etc/linux-systemd/system/syncthing@.service $installdir/%libdir%/systemd/system/syncthing@.service
    install -Dm00644 etc/linux-systemd/user/syncthing.service $installdir/%libdir%/systemd/user/syncthing.service
    # Install man pages
    cd man
    install -Dm00644 syncthing.1 $installdir/usr/share/man/man1/syncthing.1
    for file in $(find . -name '*.5' -print); do
        install -Dm00644 $file $installdir/usr/share/man/man5/$file
    done
    for file in $(find . -name '*.7' -print); do
        install -Dm00644 $file $installdir/usr/share/man/man7/$file
    done

