name       : syncthing
version    : 0.14.3
release    : 1
homepage   : https://syncthing.net
source     :
    - https://github.com/syncthing/syncthing/releases/download/v0.14.3/syncthing-linux-amd64-v0.14.3.tar.gz : 8e73dca01ddd866247eeaf963abffe1977793c864f2e86466bb02777b49bd6cf
license    : MPL-2.0
component  : network.util
summary    : Syncthing is an open-source file synchronization client/server application
description: |
    Syncthing is an open-source file synchronization client/server application,
    written in Go, implementing its own, equally free Block Exchange Protocol.
    All transit communications between syncthing nodes are encrypted,
    and all nodes are uniquely identified with cryptographic certificates.
install    : |
    install -Dm00755 syncthing $installdir/usr/bin/syncthing
    install -Dm00644 etc/linux-systemd/system/syncthing@.service $installdir/%libdir%/systemd/system/syncthing@.service
    #systemd user sessions are not running so this is not needed
    #install -Dm00644 etc/linux-systemd/user/syncthing.service $installdir/%libdir%/systemd/user/syncthing.service
