name       : syncthing
version    : 0.14.3
release    : 2
homepage   : https://syncthing.net
source     :
    - https://github.com/syncthing/syncthing/releases/download/v0.14.3/syncthing-source-v0.14.3.tar.gz : eac0c5457e266c5681e1002a764d75e1a4cbacc7a92c089ee83241c632df878e
license    : MPL-2.0
extract    : no
component  : network.util
summary    : Syncthing is an open-source file synchronization client/server application
description: |
    Syncthing is an open-source file synchronization client/server application, written in Go, implementing its own, equally free Block Exchange Protocol. All transit communications between syncthing nodes are encrypted, and all nodes are uniquely identified with cryptographic certificates.
builddeps  :
    - golang
build      : |
    export GOPATH="${workdir}" GOROOT_FINAL="/usr/bin"
    export syncdir="${workdir}/src/github.com/syncthing/"
    mkdir -p $syncdir
    tar -xf $sources/syncthing-source-v${version}.tar.gz -C $syncdir
    cd $syncdir/syncthing
    go run build.go -no-upgrade -version v${version} build
install    : |
    export syncdir="${workdir}/src/github.com/syncthing/"
    cd $syncdir/syncthing
    # Install binaries and systemd stuff
    install -Dm00755 syncthing $installdir/usr/bin/syncthing
    install -Dm00644 etc/linux-systemd/system/syncthing@.service $installdir/%libdir%/systemd/system/syncthing@.service
    # Install man pages
    cd man
    install -Dm0644 syncthing.1 $installdir/usr/share/man/man1/syncthing.1
    for file in $(find . -name '*.5' -print); do
        install -Dm0644 $file $installdir/usr/share/man/man5/$file
    done
    for file in $(find . -name '*.7' -print); do
        install -Dm644 $file $installdir/usr/share/man/man7/$file
    done
